#!/bin/bash
# Script to view all source code files

echo "=========================================="
echo "InsureHub - Source Code Viewer"
echo "=========================================="
echo ""
echo "All source code is located in: /app/"
echo ""
echo "Key Files:"
echo ""
echo "BACKEND:"
echo "  /app/backend/server.py          (950+ lines - Main backend)"
echo "  /app/backend/requirements.txt   (Python dependencies)"
echo "  /app/backend/.env               (Configuration)"
echo ""
echo "FRONTEND:"
echo "  /app/frontend/src/App.js        (Main React app)"
echo "  /app/frontend/src/auth.js       (Authentication)"
echo ""
echo "FRONTEND PAGES:"
echo "  /app/frontend/src/pages/HRDashboard.js"
echo "  /app/frontend/src/pages/SubmitEndorsement.js"
echo "  /app/frontend/src/pages/MyEndorsements.js"
echo "  /app/frontend/src/pages/ImportEndorsements.js"
echo "  /app/frontend/src/pages/AdminDashboard.js"
echo "  /app/frontend/src/pages/ApproveEndorsements.js"
echo "  /app/frontend/src/pages/AllEndorsements.js"
echo "  /app/frontend/src/pages/PoliciesManagement.js"
echo "  /app/frontend/src/pages/DownloadApproved.js"
echo ""
echo "DOCUMENTATION:"
echo "  /app/README.md                  (Complete documentation)"
echo "  /app/DEPLOYMENT_GUIDE.md        (Deployment guide)"
echo "  /app/SOURCE_CODE_GUIDE.md       (This guide)"
echo ""
echo "=========================================="
echo "To view any file, use: cat <filepath>"
echo "Example: cat /app/backend/server.py"
echo "=========================================="
