"""
Test Claims Management - New Fields (Iteration 26)
Tests for updated claims Excel import template with new fields:
- Employee Name, Patient Name, Incurred Amount, Paid Amount
- Claim Number from Excel (not auto-generated)
- Annual Claims Trend formula: (Claims / No of Days) * 365 * 1.1
"""
import pytest
import requests
import os
import io
import pandas as pd

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')

@pytest.fixture(scope="module")
def admin_token():
    """Get admin authentication token"""
    response = requests.post(f"{BASE_URL}/api/auth/login", json={
        "username": "masteradmin",
        "password": "Admin@123"
    })
    assert response.status_code == 200, f"Admin login failed: {response.text}"
    return response.json()["access_token"]

@pytest.fixture(scope="module")
def hr_token():
    """Get HR user authentication token"""
    response = requests.post(f"{BASE_URL}/api/auth/login", json={
        "username": "arpita",
        "password": "Password@123"
    })
    assert response.status_code == 200, f"HR login failed: {response.text}"
    return response.json()["access_token"]

@pytest.fixture(scope="module")
def admin_headers(admin_token):
    return {"Authorization": f"Bearer {admin_token}"}

@pytest.fixture(scope="module")
def hr_headers(hr_token):
    return {"Authorization": f"Bearer {hr_token}"}


class TestClaimsNewFields:
    """Test claims CRUD with new fields: employee_name, patient_name, incurred_amount, paid_amount"""
    
    def test_create_claim_with_new_fields(self, admin_headers):
        """POST /api/claims - Create claim with new fields"""
        payload = {
            "policy_number": "GMC0001393000100",
            "claim_number": "TEST-CLM-001",
            "claim_type": "Cashless",
            "policy_type": "ESKP",
            "claims_report_date": "2026-01-15",
            "employee_name": "Test Employee",
            "patient_name": "Test Patient",
            "claimed_amount": 100000,
            "incurred_amount": 85000,
            "paid_amount": 80000,
            "status": "Settled",
            "remarks": "Test claim with new fields"
        }
        response = requests.post(f"{BASE_URL}/api/claims", json=payload, headers=admin_headers)
        assert response.status_code == 200, f"Create claim failed: {response.text}"
        
        data = response.json()
        # Verify new fields are returned
        assert data["employee_name"] == "Test Employee", "employee_name not saved"
        assert data["patient_name"] == "Test Patient", "patient_name not saved"
        assert data["incurred_amount"] == 85000, "incurred_amount not saved"
        assert data["paid_amount"] == 80000, "paid_amount not saved"
        assert data["claim_number"] == "TEST-CLM-001", "claim_number should use provided value"
        
        # Cleanup
        claim_id = data["id"]
        requests.delete(f"{BASE_URL}/api/claims/{claim_id}", headers=admin_headers)
        print("PASS: Create claim with new fields")
    
    def test_get_claims_returns_new_fields(self, admin_headers):
        """GET /api/claims - Returns claims with new fields"""
        response = requests.get(f"{BASE_URL}/api/claims", headers=admin_headers)
        assert response.status_code == 200, f"Get claims failed: {response.text}"
        
        claims = response.json()
        if len(claims) > 0:
            claim = claims[0]
            # Check that new fields exist in response (may be null)
            assert "employee_name" in claim, "employee_name field missing"
            assert "patient_name" in claim, "patient_name field missing"
            assert "incurred_amount" in claim, "incurred_amount field missing"
            assert "paid_amount" in claim, "paid_amount field missing"
            print(f"PASS: GET /api/claims returns new fields. First claim: {claim.get('claim_number')}")
        else:
            print("PASS: GET /api/claims works (no claims in DB)")
    
    def test_claim_number_from_excel_not_autogenerated(self, admin_headers):
        """POST /api/claims - Claim Number from request is used (not auto-generated)"""
        custom_claim_number = "CUSTOM-CLM-12345"
        payload = {
            "policy_number": "GMC0001393000100",
            "claim_number": custom_claim_number,
            "claim_type": "Reimbursement",
            "claimed_amount": 50000,
            "status": "Submitted"
        }
        response = requests.post(f"{BASE_URL}/api/claims", json=payload, headers=admin_headers)
        assert response.status_code == 200, f"Create claim failed: {response.text}"
        
        data = response.json()
        assert data["claim_number"] == custom_claim_number, f"Expected {custom_claim_number}, got {data['claim_number']}"
        
        # Cleanup
        requests.delete(f"{BASE_URL}/api/claims/{data['id']}", headers=admin_headers)
        print("PASS: Claim number from request is used (not auto-generated)")


class TestClaimsTemplateDownload:
    """Test claims template download has new columns"""
    
    def test_template_has_new_columns(self, admin_headers):
        """GET /api/claims/template/download - Template has new columns"""
        response = requests.get(f"{BASE_URL}/api/claims/template/download", headers=admin_headers)
        assert response.status_code == 200, f"Template download failed: {response.text}"
        
        # Parse the Excel file
        df = pd.read_excel(io.BytesIO(response.content))
        columns = list(df.columns)
        
        # Check for new columns
        expected_columns = [
            "Policy Number", "Claim Number", "Claim Type", "Policy Type",
            "Claims Report Date", "Employee Name", "Patient Name",
            "Claimed Amount", "Incurred Amount", "Paid Amount", "Status", "Remarks"
        ]
        
        for col in expected_columns:
            assert col in columns, f"Missing column: {col}"
        
        # Verify old columns are NOT present
        old_columns = ["Cashless Claims Count", "Reimbursement Claims Count", "Approved Amount", "Settled Amount"]
        for col in old_columns:
            assert col not in columns, f"Old column should be removed: {col}"
        
        print(f"PASS: Template has correct columns: {columns}")


class TestClaimsImport:
    """Test claims import with new template fields"""
    
    def test_import_with_new_fields(self, admin_headers):
        """POST /api/claims/import - Import with new template fields"""
        # Create test Excel file with new fields
        data = {
            "Policy Number": ["GMC0001393000100"],
            "Claim Number": ["IMPORT-TEST-001"],
            "Claim Type": ["Cashless"],
            "Policy Type": ["ESKP"],
            "Claims Report Date": ["2026-01-15"],
            "Employee Name": ["Import Employee"],
            "Patient Name": ["Import Patient"],
            "Claimed Amount": [150000],
            "Incurred Amount": [120000],
            "Paid Amount": [110000],
            "Status": ["Settled"],
            "Remarks": ["Imported via test"]
        }
        df = pd.DataFrame(data)
        
        # Save to bytes
        output = io.BytesIO()
        df.to_excel(output, index=False)
        output.seek(0)
        
        files = {"file": ("test_claims.xlsx", output, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")}
        response = requests.post(f"{BASE_URL}/api/claims/import", files=files, headers=admin_headers)
        assert response.status_code == 200, f"Import failed: {response.text}"
        
        result = response.json()
        assert result["success_count"] >= 1, f"Expected at least 1 success, got {result['success_count']}"
        
        # Verify the imported claim has new fields
        claims_response = requests.get(f"{BASE_URL}/api/claims", headers=admin_headers)
        claims = claims_response.json()
        
        imported_claim = next((c for c in claims if c.get("claim_number") == "IMPORT-TEST-001"), None)
        if imported_claim:
            assert imported_claim["employee_name"] == "Import Employee", "employee_name not imported"
            assert imported_claim["patient_name"] == "Import Patient", "patient_name not imported"
            assert imported_claim["incurred_amount"] == 120000, "incurred_amount not imported"
            assert imported_claim["paid_amount"] == 110000, "paid_amount not imported"
            
            # Cleanup
            requests.delete(f"{BASE_URL}/api/claims/{imported_claim['id']}", headers=admin_headers)
        
        print(f"PASS: Import with new fields - {result['success_count']} claims imported")


class TestClaimsAnalytics:
    """Test claims analytics with new fields and formula"""
    
    def test_analytics_returns_incurred_and_paid_totals(self, admin_headers):
        """GET /api/claims-analytics - Returns total_incurred_amount and total_paid_amount"""
        response = requests.get(f"{BASE_URL}/api/claims-analytics", headers=admin_headers)
        assert response.status_code == 200, f"Analytics failed: {response.text}"
        
        data = response.json()
        
        # Check new fields exist
        assert "total_incurred_amount" in data, "total_incurred_amount missing"
        assert "total_paid_amount" in data, "total_paid_amount missing"
        assert "total_policy_days" in data, "total_policy_days missing"
        assert "annual_claims_trend" in data, "annual_claims_trend missing"
        
        print(f"PASS: Analytics returns new fields - incurred: {data['total_incurred_amount']}, paid: {data['total_paid_amount']}, days: {data['total_policy_days']}, trend: {data['annual_claims_trend']}")
    
    def test_annual_claims_trend_formula(self, admin_headers):
        """GET /api/claims-analytics - Annual Claims Trend uses correct formula"""
        response = requests.get(f"{BASE_URL}/api/claims-analytics", headers=admin_headers)
        assert response.status_code == 200, f"Analytics failed: {response.text}"
        
        data = response.json()
        
        total_claimed = data.get("total_claimed_amount", 0)
        total_policy_days = data.get("total_policy_days", 0)
        annual_claims_trend = data.get("annual_claims_trend", 0)
        
        # Verify formula: (Claims / No of Days) * 365 * 1.1
        if total_policy_days > 0:
            expected_trend = round((total_claimed / total_policy_days) * 365 * 1.1, 2)
            # Allow small floating point difference
            assert abs(annual_claims_trend - expected_trend) < 1, f"Formula mismatch: expected {expected_trend}, got {annual_claims_trend}"
            print(f"PASS: Annual Claims Trend formula correct - ({total_claimed} / {total_policy_days}) * 365 * 1.1 = {annual_claims_trend}")
        else:
            assert annual_claims_trend == 0, "Trend should be 0 when no policy days"
            print("PASS: Annual Claims Trend is 0 (no policy days)")


class TestExistingClaimsData:
    """Test existing claims data from user's Excel template"""
    
    def test_existing_claims_have_new_fields(self, admin_headers):
        """Verify existing claims (A234, C456, C458) have new fields"""
        response = requests.get(f"{BASE_URL}/api/claims", headers=admin_headers)
        assert response.status_code == 200, f"Get claims failed: {response.text}"
        
        claims = response.json()
        
        # Check for expected claims from user's template
        expected_claims = {
            "A234": {"employee_name": "Jhon", "patient_name": "Jhon", "status": "Settled"},
            "C456": {"employee_name": "Albert", "patient_name": "Albert", "status": "In Process"},
            "C458": {"employee_name": "Albert", "patient_name": "Sam", "status": "Rejected"}
        }
        
        found_claims = {}
        for claim in claims:
            claim_num = claim.get("claim_number")
            if claim_num in expected_claims:
                found_claims[claim_num] = claim
        
        print(f"Found {len(found_claims)} of {len(expected_claims)} expected claims")
        
        for claim_num, expected in expected_claims.items():
            if claim_num in found_claims:
                claim = found_claims[claim_num]
                assert claim.get("employee_name") == expected["employee_name"], f"{claim_num}: employee_name mismatch"
                assert claim.get("patient_name") == expected["patient_name"], f"{claim_num}: patient_name mismatch"
                assert claim.get("status") == expected["status"], f"{claim_num}: status mismatch"
                print(f"  PASS: Claim {claim_num} has correct data")
            else:
                print(f"  INFO: Claim {claim_num} not found (may have been deleted)")


class TestHRUserAccess:
    """Test HR user access to claims"""
    
    def test_hr_can_view_assigned_policy_claims(self, hr_headers):
        """GET /api/claims - HR sees only claims for assigned policies"""
        response = requests.get(f"{BASE_URL}/api/claims", headers=hr_headers)
        assert response.status_code == 200, f"HR get claims failed: {response.text}"
        
        claims = response.json()
        print(f"PASS: HR user can view claims - {len(claims)} claims visible")
    
    def test_hr_can_view_analytics(self, hr_headers):
        """GET /api/claims-analytics - HR can view analytics"""
        response = requests.get(f"{BASE_URL}/api/claims-analytics", headers=hr_headers)
        assert response.status_code == 200, f"HR analytics failed: {response.text}"
        
        data = response.json()
        assert "total_claims" in data
        assert "annual_claims_trend" in data
        assert "total_policy_days" in data
        print(f"PASS: HR user can view analytics - {data['total_claims']} claims, trend: {data['annual_claims_trend']}")
    
    def test_hr_cannot_create_claims(self, hr_headers):
        """POST /api/claims - HR cannot create claims (Admin only)"""
        payload = {
            "policy_number": "GMC0001393000100",
            "claim_type": "Cashless",
            "claimed_amount": 10000
        }
        response = requests.post(f"{BASE_URL}/api/claims", json=payload, headers=hr_headers)
        assert response.status_code == 403, f"HR should not be able to create claims: {response.status_code}"
        print("PASS: HR cannot create claims (403 Forbidden)")
    
    def test_hr_cannot_download_template(self, hr_headers):
        """GET /api/claims/template/download - HR cannot download template (Admin only)"""
        response = requests.get(f"{BASE_URL}/api/claims/template/download", headers=hr_headers)
        assert response.status_code == 403, f"HR should not be able to download template: {response.status_code}"
        print("PASS: HR cannot download template (403 Forbidden)")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
